name: dlp_last
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  amplify_flutter: ^2.6.5
  amplify_auth_cognito: ^2.6.5
  amplify_auth_cognito_dart: ^0.11.13
  amplify_storage_s3: ^2.6.5
  amplify_core: ^2.6.5
  image_picker: ^1.1.2

  cloud_firestore: ^5.6.12
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.7.0
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^18.0.1
  flutter:
    sdk: flutter
  firebase_in_app_messaging: ^0.8.1+10
  
  

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "./assets/cybersecurity.png"

flutter:
  uses-material-design: true


