// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz7UOOTEnAg4k9pcy4KQ2Rs9Ar-zVj4YE',
    appId: '1:768920670018:web:018c416def1044b4a1c2db',
    messagingSenderId: '768920670018',
    projectId: 'dlp-0712',
    authDomain: 'dlp-0712.firebaseapp.com',
    storageBucket: 'dlp-0712.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcr3ivpdda0znYYgi1dExyMIA1JV2XpaQ',
    appId: '1:768920670018:android:5f3c9a69d5aa00d7a1c2db',
    messagingSenderId: '768920670018',
    projectId: 'dlp-0712',
    storageBucket: 'dlp-0712.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4TOPI4mApkq1xz3g1zR5239IcD37fjYo',
    appId: '1:768920670018:ios:0b534613576f7cc0a1c2db',
    messagingSenderId: '768920670018',
    projectId: 'dlp-0712',
    storageBucket: 'dlp-0712.firebasestorage.app',
    iosBundleId: 'com.example.dlpLast',
  );
}
